baseURL = '/'
languageCode = 'en-us'
title = 'Winblues'
theme = 're-terminal'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
centerTheme = true
themeColor = "paper"
favicon = "favicon.png"
#copyright = "[foobar](goo.as)"


[params.Logo]
logoText = 'Winblues'
