baseURL = '/'
languageCode = 'en-us'
title = 'Winblues'
theme = 're-terminal'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[languages.en.menu]
#  [[languages.en.menu.main]]
#    identifier = "images"
#    name = "Projects"
#    url = "/projects"
  [[languages.en.menu.main]]
    identifier = "blue95"
    name = "Blue95"
    url = "/95"
  [[languages.en.menu.main]]
    identifier = "winblues7"
    name = "Winblues 7"
    url = "https://github.com/winblues/winblues7"
  [[languages.en.menu.main]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/winblues"

[params]
centerTheme = true
themeColor = "paper"
favicon = "favicon.png"
copyright = "© Winblues 2025 :: Powered by Hugo"
showMenuItems = 5

[params.Logo]
logoText = 'Winblues'
