site_name: Blue95
site_url: https://blues.win/95/docs/
nav:
    - Home: 'index.md'
    - Install: 'install.md'
    - Showcase: 'screenshots.md'
    - GitHub: 'https://github.com/winblues/blue95'
    - About:
      - Project Design: 'project.md'
      - Thanks: 'thanks.md'
    - User Guide:
      - Applications: 'applications.md'
      - Xfce Settings: 'user-configs.md'
theme:
  name: terminal
  palette: dark
  custom_dir: overrides
  features:
    - footer.prev_next
    #- navigation.side.toc.hide
    #- navigation.side.hide
    - navigation.top.cursor_animation.hide
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences          # required extension
  - pymdownx.highlight:
      use_pygments: true          # use pygments library    
      pygments_style: github-dark # use 'github-dark' style
      noclasses: true             # update HTML style attr
  - pymdownx.inlinehilite         # style inline code
  - pymdownx.blocks.details:
      types:
        - name: tip
          class: terminal-alert
          title: Tip
        - name: info
          class: terminal-alert
          title: Info
        - name: warn
          class: 'terminal-alert terminal-alert-error'
          title: Warning
        - name: important
          class: 'terminal-alert terminal-alert-primary'
          title: Important
